-- dbt Cloud observability landing tables (Snowflake).
-- Placeholder {{OBS_SCHEMA}} is replaced at runtime (unquoted identifier, uppercase recommended).

CREATE SCHEMA IF NOT EXISTS {{OBS_SCHEMA}};

CREATE TABLE IF NOT EXISTS {{OBS_SCHEMA}}.DBT_RUNS (
    RUN_ID NUMBER(38,0) NOT NULL,
    ACCOUNT_ID VARCHAR(64),
    JOB_DEFINITION_ID NUMBER(38,0),
    JOB_NAME VARCHAR(512),
    ENVIRONMENT_ID NUMBER(38,0),
    PROJECT_ID NUMBER(38,0),
    STATUS NUMBER(38,0),
    STATUS_HUMANIZED VARCHAR(128),
    IS_ERROR BOOLEAN,
    IS_CANCELLED BOOLEAN,
    SHOULD_FULL_REFRESH BOOLEAN,
    GIT_BRANCH VARCHAR(512),
    GIT_SHA VARCHAR(128),
    CREATED_AT TIMESTAMP_NTZ(9),
    UPDATED_AT TIMESTAMP_NTZ(9),
    STARTED_AT TIMESTAMP_NTZ(9),
    FINISHED_AT TIMESTAMP_NTZ(9),
    RUN_DURATION_MS NUMBER(38,0),
    QUEUED_DURATION_MS NUMBER(38,0),
    LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DBT_RUNS PRIMARY KEY (RUN_ID)
);

CREATE TABLE IF NOT EXISTS {{OBS_SCHEMA}}.DBT_RUN_STEPS (
    STEP_ID NUMBER(38,0) NOT NULL,
    RUN_ID NUMBER(38,0) NOT NULL,
    STEP_INDEX NUMBER(38,0),
    STEP_NAME VARCHAR(512),
    STATUS VARCHAR(64),
    STATUS_HUMANIZED VARCHAR(128),
    STARTED_AT TIMESTAMP_NTZ(9),
    FINISHED_AT TIMESTAMP_NTZ(9),
    LOGS_TEXT VARCHAR(16777216),
    DEBUG_LOGS_TEXT VARCHAR(16777216),
    LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DBT_RUN_STEPS PRIMARY KEY (STEP_ID)
);

CREATE TABLE IF NOT EXISTS {{OBS_SCHEMA}}.DBT_NODE_RESULTS (
    RESULT_KEY VARCHAR(128) NOT NULL,
    RUN_ID NUMBER(38,0) NOT NULL,
    UNIQUE_ID VARCHAR(512),
    RESOURCE_TYPE VARCHAR(64),
    NODE_NAME VARCHAR(512),
    STATUS VARCHAR(64),
    EXECUTION_TIME_SECONDS FLOAT,
    MESSAGE VARCHAR(16777216),
    ROWS_AFFECTED NUMBER(38,0),
    ROWS_INSERTED NUMBER(38,0),
    ROWS_UPDATED NUMBER(38,0),
    ROWS_DELETED NUMBER(38,0),
    THREAD_ID VARCHAR(64),
    COMPILED_SQL VARCHAR(16777216),
    LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DBT_NODE_RESULTS PRIMARY KEY (RESULT_KEY)
);
